### ISSUE TITLE
About ReadMe file

### ISSUE THREAD

**Issue by ZhuyuLICFC** [minzhou1003/ec601-project#4]
For your README file, It is good to provide a configuration guidance for a beginner user just like me.  But when following the instructions, I faced some problems, you may want to modify corresponding parts at your README file:

1. Some incorrect file names:
![image](https://user-images.githubusercontent.com/43104514/47958141-922abf00-df9b-11e8-9f5d-96687c959bd9.png) 
I think it is ec601-project.

![image](https://user-images.githubusercontent.com/43104514/47958154-b9818c00-df9b-11e8-9a3c-1edd802d6680.png)
For me, the folder name I downloaded is called "all" instead of input. I need to do the modification to avoid the run time error.

2. You may also consider to add the instruction of installing Jupyter Notebook before  step3, I face the "Invalid requirement: 'jupyter notebook'" error when doing step 3, so I can only add those packages manually.

3. My operating system is Windows,  and I also need a configuration of the Jupyter‘s ’work path before run it, Not sure if it just happens to me.

Thanks for the guidance anyway.

**Comment by minzhou1003** [comment]
Hi, thanks for your comments.

1. Yeah, it should be `cd ec601-project`. The folder you download from kaggle should be renamed to `input`,  and I just updated new README.md. 
2. Did you pull from the latest `requirements.txt`? It includes the jupyter notebook.
3. All the code is only tested on Linux, your operating system may not fit. You may want to try a virtual machine. I'll also add those comment to our README.
